CREATE TABLE IF NOT EXISTS users (
    id BIGINT  GENERATED ALWAYS AS IDENTITY  PRIMARY KEY ,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);