CREATE TABLE IF NOT EXISTS cloud_providers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    provider_name VARCHAR(50) NOT NULL UNIQUE,

    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);